"use client";
import { useMemo, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { Check, Clipboard, ExternalLink, Wrench } from "lucide-react";
import { ProtectedLayout } from "@/components/layout/ProtectedLayout";
import { StatusBadge } from "@/components/ui/StatusBadge";
import { useAuth } from "@/contexts/AuthContext";
import { useAuthFetch } from "@/hooks/useAuthFetch";
import { cn, formatCost, formatDateTime, formatDuration, formatTokens } from "@/lib/utils";
type JsonValue=string|number|boolean|null|JsonValue[]|{[key:string]:JsonValue};
interface ToolCall{id:number;tool_name:string;status:string;duration_ms:number|null;input_data:JsonValue|null;output_data:JsonValue|null;requires_approval:boolean;approval_id?:number|null;blocked_reason:string|null}interface ModelCall{id:number;provider:string;model:string;input_tokens:number;output_tokens:number;estimated_cost:number;pricing_status:"PRICED"|"UNPRICED";latency_ms:number|null;status:string}interface Span{id:number;external_span_id:string|null;parent_span_id:number|null;name:string;type:string;status:string;started_at:string;ended_at:string|null;duration_ms:number|null;input_data:JsonValue|null;output_data:JsonValue|null;error_data:JsonValue|null;metadata:JsonValue|null;tool_calls:ToolCall[];model_calls:ModelCall[]}interface Event{id:number;event_type:string;severity:string;message:string;created_at:string;span_id:number|null;metadata:JsonValue|null}interface CostRecord{provider:string;model:string;cost_usd:number;pricing_status:"PRICED"|"UNPRICED"}interface Trace{id:number;external_trace_id:string|null;name:string;status:string;risk_level:string;started_at:string;ended_at:string|null;duration_ms:number|null;total_input_tokens:number;total_output_tokens:number;total_cost:number;unpriced_model_calls:number;spans:Span[];events:Event[];cost_records:CostRecord[];metadata:JsonValue|null}
function flatten(spans:Span[]){const out:{span:Span;depth:number}[]=[];const walk=(parent:number|null,depth:number)=>spans.filter(s=>s.parent_span_id===parent).sort((a,b)=>Date.parse(a.started_at)-Date.parse(b.started_at)).forEach(span=>{out.push({span,depth});walk(span.id,depth+1)});walk(null,0);return out.length?out:spans.map(span=>({span,depth:0}))}
function JsonViewer({label,value}:{label:string;value:JsonValue|null}){const[copied,setCopied]=useState(false);if(value==null)return null;const text=JSON.stringify(value,null,2);return <section className="json-section"><div><h3>{label}</h3><button onClick={async()=>{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),1200)}} aria-label={`Copy ${label}`}><>{copied?<Check size={13}/>:<Clipboard size={13}/>}</>{copied?"Copied":"Copy"}</button></div><pre>{text}</pre></section>}
export default function TraceDetailPage(){const{id}=useParams<{id:string}>();const{activeOrg}=useAuth();const api=useAuthFetch();const{data:trace,isLoading,isError,refetch}=useQuery<Trace>({queryKey:["trace",id],queryFn:()=>api.get(`/api/v1/organizations/${activeOrg!.id}/traces/${id}`),enabled:!!activeOrg});const[selectedId,setSelectedId]=useState<number|null>(null);const rows=useMemo(()=>flatten(trace?.spans??[]),[trace]);const selected=trace?.spans.find(s=>s.id===(selectedId??rows[0]?.span.id));if(isLoading)return <ProtectedLayout><div><div className="detail-skeleton"/></div></ProtectedLayout>;if(isError||!trace)return <ProtectedLayout><div><div className="query-error"><strong>Trace could not be loaded.</strong><button onClick={()=>refetch()}>Try again</button></div></div></ProtectedLayout>;const origin=Date.parse(trace.started_at);const total=Math.max(trace.duration_ms??Math.max(...trace.spans.map(s=>(s.duration_ms??0)),1),1);return <ProtectedLayout><div className="trace-detail">
 <div className="trace-breadcrumb"><Link href="/traces">Traces</Link><span>/</span><code>{trace.external_trace_id??`#${trace.id}`}</code></div>
 <header className="trace-hero"><div className="trace-title"><div><h1>{trace.name}</h1><code>{trace.external_trace_id??`trace-${trace.id}`}</code></div><StatusBadge status={trace.status}/></div><dl><div><dt>Started</dt><dd>{formatDateTime(trace.started_at)}</dd></div><div><dt>Duration</dt><dd>{formatDuration(trace.duration_ms)}</dd></div><div><dt>Tokens</dt><dd>{formatTokens(trace.total_input_tokens+trace.total_output_tokens)}</dd></div><div><dt>{trace.unpriced_model_calls?"Known cost":"Cost"}</dt><dd>{formatCost(trace.total_cost)}</dd></div><div><dt>Risk</dt><dd><StatusBadge status={trace.risk_level}/></dd></div><div><dt>Spans</dt><dd>{trace.spans.length}</dd></div></dl>{trace.unpriced_model_calls>0&&<div className="cost-warning">{trace.unpriced_model_calls} model {trace.unpriced_model_calls===1?"call is":"calls are"} unpriced. Displayed cost is incomplete.</div>}</header>
 <div className="trace-workspace"><section className="waterfall-panel"><div className="panel-heading"><div><h2>Execution timeline</h2><p>Span timing relative to the full trace.</p></div><span>{formatDuration(total)}</span></div><div className="waterfall-scroll"><div className="waterfall-axis"><span>0ms</span><span>{formatDuration(total/2)}</span><span>{formatDuration(total)}</span></div>{rows.length?rows.map(({span,depth})=>{const offset=Math.max(0,((Date.parse(span.started_at)-origin)/total)*100);const width=Math.max(1.2,((span.duration_ms??0)/total)*100);return <button key={span.id} onClick={()=>setSelectedId(span.id)} className={cn("waterfall-row",selected?.id===span.id&&"is-selected")}><span className="waterfall-name" style={{paddingLeft:12+depth*16}}><small>{span.type}</small><strong>{span.name}</strong></span><span className="waterfall-track"><i className={cn(span.status.toLowerCase())} style={{left:`${Math.min(offset,98)}%`,width:`${Math.min(width,100-offset)}%`}}/><em>{formatDuration(span.duration_ms)}</em></span></button>}):<div className="empty-row">No spans recorded for this trace.</div>}</div></section>
 <aside className="span-inspector">{selected?<><div className="inspector-heading"><div><small>{selected.type}</small><h2>{selected.name}</h2></div><StatusBadge status={selected.status}/></div><dl className="span-facts"><div><dt>Duration</dt><dd>{formatDuration(selected.duration_ms)}</dd></div><div><dt>Started</dt><dd>{formatDateTime(selected.started_at)}</dd></div></dl>{selected.tool_calls.map(call=><section key={call.id} className="call-block"><div><Wrench size={14}/><strong>{call.tool_name}</strong><StatusBadge status={call.status}/></div>{call.blocked_reason&&<p className="blocked-reason">{call.blocked_reason}</p>}{call.approval_id&&<Link href="/approvals">Approval #{call.approval_id}<ExternalLink size={12}/></Link>}<JsonViewer label="Tool input" value={call.input_data}/><JsonViewer label="Tool output" value={call.output_data}/></section>)}{selected.model_calls.map(call=><section key={call.id} className="model-call"><div><span><strong>{call.provider}</strong><code>{call.model}</code></span><StatusBadge status={call.pricing_status}/></div><dl><div><dt>Tokens in</dt><dd>{formatTokens(call.input_tokens)}</dd></div><div><dt>Tokens out</dt><dd>{formatTokens(call.output_tokens)}</dd></div><div><dt>Latency</dt><dd>{formatDuration(call.latency_ms)}</dd></div><div><dt>Authoritative cost</dt><dd>{call.pricing_status==="UNPRICED"?"Unpriced":formatCost(call.estimated_cost)}</dd></div></dl></section>)}<JsonViewer label="Input" value={selected.input_data}/><JsonViewer label="Output" value={selected.output_data}/><JsonViewer label="Error" value={selected.error_data}/><JsonViewer label="Metadata" value={selected.metadata}/>{!selected.tool_calls.length&&!selected.model_calls.length&&selected.input_data==null&&selected.output_data==null&&selected.error_data==null&&selected.metadata==null&&<div className="empty-inspector">No additional data captured for this span.</div>}</>:<div className="empty-inspector">Select a span to inspect its data.</div>}</aside></div>
 {trace.events.length>0&&<section className="ops-panel event-log"><div className="panel-heading"><div><h2>Trace events</h2><p>Security and runtime events in sequence.</p></div></div>{trace.events.map(event=><div className="event-row" key={event.id}><StatusBadge status={event.severity}/><code>{new Date(event.created_at).toLocaleTimeString()}</code><strong>{event.event_type}</strong><span>{event.message}</span></div>)}</section>}
 </div></ProtectedLayout>}
