"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Activity, ArrowRight, CheckCircle2, ShieldCheck } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";
import { ApiError } from "@/lib/api";

export default function LoginPage(){const{login,organizations}=useAuth();const router=useRouter();const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState<string|null>(null);const[loading,setLoading]=useState(false);async function submit(event:React.FormEvent){event.preventDefault();setError(null);setLoading(true);try{await login(email,password);router.push(organizations.length>1?"/select-organization":"/dashboard")}catch(reason){setError(reason instanceof ApiError&&reason.status===429?"Account temporarily locked. Try again later.":reason instanceof ApiError?"Email or password is incorrect.":"AgentOps is unavailable. Check the service and try again.")}finally{setLoading(false)}}return <main className="login-shell">
 <section className="login-context"><div className="login-brand"><span className="brand-mark"><span/></span><span><strong>AgentOps</strong><small>Monitor</small></span></div><div className="login-statement"><h1>Operate AI agents with clarity.</h1><p>Observe executions, govern risk, and evaluate quality from one connected control plane.</p><ul><li><Activity size={15}/>Trace every agent decision</li><li><ShieldCheck size={15}/>Control tools, policy, and security</li><li><CheckCircle2 size={15}/>Compare quality and known cost</li></ul></div><small className="login-footnote">AI operations console</small></section>
 <section className="login-form-region"><form onSubmit={submit} className="login-form"><header><h2>Sign in</h2><p>Continue to your organization workspace.</p></header>{error&&<div className="login-error" role="alert">{error}</div>}<label>Email address<input name="email" type="email" autoComplete="email" spellCheck={false} required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com"/></label><label>Password<input name="password" type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password"/></label><button type="submit" disabled={loading}>{loading?"Signing in…":<>Sign in <ArrowRight size={15}/></>}</button></form></section>
 </main>}
