"use client";
import { useEffect,useState,type ReactNode } from "react";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { Database,Globe2,ShieldCheck,Wrench,Zap } from "lucide-react";
import { useAuthFetch } from "@/hooks/useAuthFetch";
type Action="detect"|"redact"|"alert"|"block";
interface AgentPolicy{id:number;agent_id:number;allowed_tools:string[]|null;blocked_tools:string[]|null;tools_requiring_approval:string[]|null;allowed_domains:string[]|null;blocked_domains:string[]|null;max_tokens_per_trace:number|null;max_cost_per_trace_usd:number|null;capture_inputs:boolean;capture_outputs:boolean;pii_action:Action;secret_action:Action;injection_action:Action;active:boolean}
const csv=(value:string)=>Array.from(new Set(value.split(",").map(item=>item.trim().toLowerCase()).filter(Boolean)));const text=(value:string[]|null|undefined)=>(value??[]).join(", ");
function Group({icon,title,description,children}:{icon:ReactNode;title:string;description:string;children:ReactNode}){return <fieldset className="policy-group"><legend><span>{icon}</span><span><strong>{title}</strong><small>{description}</small></span></legend><div className="policy-fields">{children}</div></fieldset>}
export function AgentPolicyEditor({orgId,agentId}:{orgId:number;agentId:number}){const api=useAuthFetch();const qc=useQueryClient();const key=["agent-policy",orgId,agentId];const{data,isLoading}=useQuery<{items:AgentPolicy[]}>({queryKey:key,queryFn:()=>api.get(`/api/v1/organizations/${orgId}/security/policies?agent_id=${agentId}`)});const policy=data?.items[0];const[form,setForm]=useState({allowed_tools:"",blocked_tools:"",tools_requiring_approval:"",allowed_domains:"",blocked_domains:"",max_tokens_per_trace:"",max_cost_per_trace_usd:"",capture_inputs:true,capture_outputs:true,pii_action:"alert" as Action,secret_action:"block" as Action,injection_action:"alert" as Action,active:true});useEffect(()=>{if(policy)setForm({allowed_tools:text(policy.allowed_tools),blocked_tools:text(policy.blocked_tools),tools_requiring_approval:text(policy.tools_requiring_approval),allowed_domains:text(policy.allowed_domains),blocked_domains:text(policy.blocked_domains),max_tokens_per_trace:policy.max_tokens_per_trace?.toString()??"",max_cost_per_trace_usd:policy.max_cost_per_trace_usd?.toString()??"",capture_inputs:policy.capture_inputs,capture_outputs:policy.capture_outputs,pii_action:policy.pii_action,secret_action:policy.secret_action,injection_action:policy.injection_action,active:policy.active})},[policy]);const set=<K extends keyof typeof form>(field:K,value:(typeof form)[K])=>setForm(current=>({...current,[field]:value}));const save=useMutation({mutationFn:()=>{const payload={agent_id:agentId,allowed_tools:csv(form.allowed_tools),blocked_tools:csv(form.blocked_tools),tools_requiring_approval:csv(form.tools_requiring_approval),allowed_domains:csv(form.allowed_domains),blocked_domains:csv(form.blocked_domains),max_tokens_per_trace:form.max_tokens_per_trace===""?null:Number(form.max_tokens_per_trace),max_cost_per_trace_usd:form.max_cost_per_trace_usd===""?null:Number(form.max_cost_per_trace_usd),capture_inputs:form.capture_inputs,capture_outputs:form.capture_outputs,pii_action:form.pii_action,secret_action:form.secret_action,injection_action:form.injection_action,active:form.active};const path=`/api/v1/organizations/${orgId}/security/policies${policy?`/${policy.id}`:""}`;return policy?api.patch(path,payload):api.post(path,payload)},onSuccess:()=>qc.invalidateQueries({queryKey:key})});const field="w-full border px-3 py-2 text-sm";if(isLoading)return <div className="policy-loading">Loading policy…</div>;return <section className="policy-editor"><header><div><h2>Enforcement policy</h2><p>Preflight controls applied before and during every trace.</p></div><label className="policy-switch"><input type="checkbox" checked={form.active} onChange={e=>set("active",e.target.checked)}/><span>Policy active</span></label></header><div className="policy-groups">
<Group icon={<Wrench size={15}/>} title="Tool access" description="Allow, block, or require one-time review."><label>Allowed tools<input className={field} value={form.allowed_tools} onChange={e=>set("allowed_tools",e.target.value)} placeholder="search, read_record…"/></label><label>Blocked tools<input className={field} value={form.blocked_tools} onChange={e=>set("blocked_tools",e.target.value)} placeholder="shell_exec…"/></label><label>Approval required<input className={field} value={form.tools_requiring_approval} onChange={e=>set("tools_requiring_approval",e.target.value)} placeholder="send_email…"/></label></Group>
<Group icon={<Globe2 size={15}/>} title="Domains" description="Constrain network targets for tool calls."><label>Allowed domains<input className={field} value={form.allowed_domains} onChange={e=>set("allowed_domains",e.target.value)} placeholder="api.example.com…"/></label><label>Blocked domains<input className={field} value={form.blocked_domains} onChange={e=>set("blocked_domains",e.target.value)} placeholder="untrusted.example…"/></label></Group>
<Group icon={<Database size={15}/>} title="Data capture" description="Choose which sanitized payloads become observable."><label className="check-row"><input type="checkbox" checked={form.capture_inputs} onChange={e=>set("capture_inputs",e.target.checked)}/><span><strong>Capture inputs</strong><small>Store sanitized span and call inputs.</small></span></label><label className="check-row"><input type="checkbox" checked={form.capture_outputs} onChange={e=>set("capture_outputs",e.target.checked)}/><span><strong>Capture outputs</strong><small>Store sanitized span and call outputs.</small></span></label></Group>
<Group icon={<ShieldCheck size={15}/>} title="Security actions" description="Response when a detector matches.">{(["pii_action","secret_action","injection_action"] as const).map(name=><label key={name}>{name==="pii_action"?"Personal data":name==="secret_action"?"Secrets":"Prompt injection"}<select className={field} value={form[name]} onChange={e=>set(name,e.target.value as Action)}>{(["detect","redact","alert","block"] as Action[]).map(action=><option key={action}>{action}</option>)}</select></label>)}</Group>
<Group icon={<Zap size={15}/>} title="Resource limits" description="Stop traces that exceed approved budgets."><label>Token limit per trace<input type="number" min="0" className={field} value={form.max_tokens_per_trace} onChange={e=>set("max_tokens_per_trace",e.target.value)} placeholder="Unlimited"/></label><label>Cost limit per trace (USD)<input type="number" min="0" step="0.000001" className={field} value={form.max_cost_per_trace_usd} onChange={e=>set("max_cost_per_trace_usd",e.target.value)} placeholder="Unlimited"/></label></Group>
</div><footer><span aria-live="polite">{save.isError?"Policy could not be saved. Review the values and try again.":save.isSuccess?"Policy saved and active for new traces.":""}</span><button onClick={()=>save.mutate()} disabled={save.isPending}>{save.isPending?"Saving…":policy?"Save policy":"Create policy"}</button></footer></section>}
